En documentation
yiisoft/test-support pull request #21
Opened 2020-12-14 09:00 UTC by wiperawa

| Q             | A
| ------------- | ---
| Is bugfix?    |❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
>  The preferred way to install this package is through [composer](https://getcomposer.org/download/):
```suggestion
The preferred way to install this package is through [Composer](https://getcomposer.org/download/):
```

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
> +This is simple dependency container, the configuration for which you pass in the constructor.
```suggestion
This is simple dependency container, the definitions configuration for which you pass in the constructor.
```

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
> +simultaneously, the dispatcher is PSR-compliant and consider `StoppableEventInterface`.
```suggestion
Simultaneously, the dispatcher is PSR-compliant and consider `StoppableEventInterface`.
```

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
> +If your code sent as event to `SimpleEventDispatcher`, then in tests you can check this using the following methods:
```suggestion
If your code sent an event to `SimpleEventDispatcher`, then in tests you can check this using the following methods:
```

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
> +- `isClassTriggered::isClassTriggered(string $class, int $times = null)` — Event of `$class` class was triggered .
```suggestion
- `isClassTriggered::isClassTriggered(string $class, int $times = null)` — Event of `$class` class was triggered.
```

2020-12-14 10:51 UTC, roxblnfk commented on docs/en/README.md
> +`MemorySimpleCache`  Does not use external storage, to store cachec values.
```suggestion
The `MemorySimpleCache`  class does not use external storage, to store cached values.
```

2020-12-14 16:00 UTC, roxblnfk approved these changes

2020-12-14 22:30 UTC, samdark requested changes

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +Some components of the codebase, during their working process, rely on services that meet the requirements of the [PSR-interfaces](https://www.php-fig.org/psr/).
```suggestion
Some components of the application codebase rely on services implementing [PSR-interfaces](https://www.php-fig.org/psr/).
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +of similar PSR implementations in test environment.
```suggestion
To test such components, the developer often has to write his own tests-sepcific versions of similar PSR implementations.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +Test Support package provide ready-to-use implementations of some PSR interfaces, intended solely to help test your code.
```suggestion
Test Support package provides ready-to-use implementations of some PSR interfaces, intended solely to help testing your code.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +This Closure will be called to get 'default' value, if the requested value is not found if the configuration:
```suggestion
The `SimpleContainer` is a simple dependency container accepting the definitions configuration as the constructor argument. Despite the simplicity, container is flexible: 2nd parameter of the constructor accepts a Closure.
This Closure will be called to get "default" value if the requested value is not found if the configuration:
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +Simultaneously, the dispatcher is PSR-compliant and consider `StoppableEventInterface`.
```suggestion
The `SimpleEventDispatcher` is a test-specific event dispatcher. You can pass any number of closure-listeners to its  constructor. SimpleEventDispatcher` does not contain any complex logic for matching an event to a listener. Every listener should decide by itself if it processes an event or not. The dispatcher is PSR-compliant and works with `StoppableEventInterface`.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +If your code sent an event to `SimpleEventDispatcher`, then in tests you can check this using the following methods:
```suggestion
You can test for events sent to `SimpleEventDispatcher` using the following methods:
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +The `MemorySimpleCache` class does not use external storage, to store cached values.
```suggestion
The `MemorySimpleCache` class does not use external storage to store cached values.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +Use `MemorySimpleCache` in the simple cases, when you dont need to keep track the history of calls to the cache.
```suggestion
Values are stored in the array property of the object itself and will be destroyed along with the object.
Use `MemorySimpleCache` in the simple cases when you do not need to keep track of the history of cache access. 
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +you can define return values for the corresponding methods of the `SimpleCacheInterface`.
```suggestion
You can simulate cache errors by setting public properties `returnOnSet`, `returnOnDelete` and `returnOnClear`. These define values returned by the corresponding methods of the `SimpleCacheInterface`.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +commands, even if they are invalid (the key contains invalid characters, or is not string at all, for example).
```suggestion
The `SimpleCacheActionLogger` class is a decorator for `SimpleCacheInterface`. It remembers all cache calls even if they are invalid such as when the key contains invalid characters, or is not a string at all. 
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +For example, when the testing service supposed to resend the value to the cache after the first failed attempt.
```suggestion
Use the decorator when it is not enough to test the cache state before and after code execution.
For example, when the testing service is supposed to resend the value to the cache after the first failed attempt.
```

2020-12-14 22:30 UTC, samdark commented on docs/en/README.md
> +//MemorySimpleCache::set() method will be returning false, which corresponds to an error, accourding to PSR
```suggestion
//MemorySimpleCache::set() method will return false, which is an error according to PSR
```

2020-12-15 14:54 UTC, merged

2020-12-15 14:54 UTC, samdark commented
Thank you!