Update `psr/log` version
yiisoft/test-support pull request #43
Opened 2022-06-05 16:24 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2022-06-06 06:09 UTC, arogachev commented on tests/Log/SimpleLoggerTest.php
>      public function testLogWithResourceMessage(): void
```suggestion
    /**
     * @requires PHP >= 8.0
     */
    public function testLogWithResourceMessage(): void
```

2022-06-06 06:09 UTC, arogachev commented on tests/Log/SimpleLoggerTest.php
>      public function testLogWithResourceMessage(): void
https://phpunit.readthedocs.io/en/9.5/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests-skipping-tests-examples-databaseclassskippingtest-php

2022-06-06 06:10 UTC, arogachev commented on tests/Log/SimpleLoggerTest.php
>      public function testPsrLogInterfaceMethods($message, string $expected): void
```suggestion
    /**
     * @requires PHP < 8.0
     */
    public function testPsrLogInterfaceMethods($message, string $expected): void
```

2022-06-06 06:10 UTC, arogachev commented on tests/Log/SimpleLoggerTest.php
>      public function testPsrLogInterfaceMethods($message, string $expected): void
https://phpunit.readthedocs.io/en/9.5/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests-skipping-tests-examples-databaseclassskippingtest-php

2022-06-06 06:12 UTC, arogachev requested changes
Could be simplified a bit (see suggestions).

2022-06-06 08:29 UTC, arogachev approved these changes

2022-06-14 15:27 UTC, roxblnfk commented on composer.json
> +        "psr/log": "^1.0|^2.0|^3.0",
```suggestion
        "psr/log": "^1.1|^2.0|^3.0",
```

2022-06-14 15:27 UTC, roxblnfk commented on tests/Log/SimpleLoggerTest.php
> +     * @requires PHP < 8.0
What is this for?

2022-06-14 15:27 UTC, roxblnfk commented on tests/Log/SimpleLoggerTest.php
> +     */
What is this for?

2022-06-14 15:52 UTC, rustamwin commented on tests/Log/SimpleLoggerTest.php
> +     * @requires PHP < 8.0
For `psr/log` ^1.1 version

2022-06-14 15:53 UTC, rustamwin commented on tests/Log/SimpleLoggerTest.php
> +     */
For `psr/log` ^1.1 version

2022-06-14 17:35 UTC, roxblnfk commented on tests/Log/SimpleLoggerTest.php
> +     * @requires PHP < 8.0
Are you sure these tests are needed?

2022-06-15 09:23 UTC, rustamwin commented on tests/Log/SimpleLoggerTest.php
> +     * @requires PHP < 8.0
Yes.

2022-06-16 07:03 UTC, samdark approved these changes

2022-06-16 14:21 UTC, merged